# Generated by Django 6.0.4 on 2026-04-12 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entreprises', '0001_initial'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_export', models.CharField(choices=[('bc_csv', 'Bons de commande CSV'), ('bc_pdf', 'Bons de commande PDF'), ('fournisseurs_csv', 'Fournisseurs CSV'), ('fournisseurs_stats', 'Statistiques fournisseurs'), ('delais_livraison', 'Rapport délais livraison'), ('predictions_csv', 'Prédictions CSV'), ('suggestions_csv', 'Suggestions achat CSV'), ('budget_previsionnel', 'Budget prévisionnel')], max_length=50)),
                ('nom_fichier', models.CharField(max_length=255)),
                ('periode', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True)),
                ('taille', models.PositiveIntegerField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprises.entreprise')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications', models.JSONField(default=dict)),
                ('devise_defaut', models.CharField(default='EUR', max_length=3)),
                ('seuil_alerte_jours', models.PositiveSmallIntegerField(default=7)),
                ('budget_mensuel', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('entrepot_defaut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.entrepot')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='achat_prefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
