# Generated by Django 6.0.4 on 2026-04-14 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responsable_achat', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExportLog',
        ),
    ]
