# Generated by Django 6.0.4 on 2026-04-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_produit_prix_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionstock',
            name='precision_mape',
            field=models.FloatField(blank=True, null=True, verbose_name='Erreur absolue moyenne (MAPE en %)'),
        ),
    ]
