# Generated by Django 6.0.4 on 2026-06-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0001_initial'),
        ('stock', '0003_predictionstock_precision_mape'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='produit',
            constraint=models.UniqueConstraint(condition=models.Q(('code_barres__gt', '')), fields=('entreprise', 'code_barres'), name='unique_code_barres_par_entreprise'),
        ),
    ]
