# Generated by Django 6.0.4 on 2026-06-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_unique_code_barres_par_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='delai_reappro',
            field=models.PositiveIntegerField(default=7, verbose_name='Délai de réapprovisionnement (jours)'),
        ),
        migrations.AddField(
            model_name='produit',
            name='qte_min_commande',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité minimale de commande'),
        ),
    ]
