# Generated by Django 6.0.4 on 2026-04-11 12:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entreprises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_notif', models.CharField(choices=[('alerte_stock', 'Alerte stock'), ('commande', 'Commande'), ('inventaire', 'Inventaire'), ('ia', 'Prédiction IA'), ('systeme', 'Système')], max_length=20)),
                ('titre', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('lue', models.BooleanField(default=False)),
                ('lien', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_action', models.CharField(choices=[('connexion', 'Connexion'), ('deconnexion', 'Déconnexion'), ('creation_user', 'Création utilisateur'), ('modification_user', 'Modification utilisateur'), ('suppression_user', 'Suppression utilisateur'), ('activation_user', 'Activation utilisateur'), ('desactivation_user', 'Désactivation utilisateur'), ('changement_role', 'Changement de rôle'), ('creation_entreprise', 'Création entreprise'), ('activation_entreprise', 'Activation entreprise'), ('desactivation_entreprise', 'Désactivation entreprise'), ('suppression_entreprise', 'Suppression entreprise'), ('creation_produit', 'Création produit'), ('modification_produit', 'Modification produit'), ('mouvement_stock', 'Mouvement de stock'), ('validation_inventaire', 'Validation inventaire'), ('creation_bc', 'Création bon de commande'), ('validation_bc', 'Validation bon de commande'), ('reception_bc', 'Réception bon de commande'), ('export', 'Export de données'), ('ia_analyse', 'Analyse IA déclenchée'), ('autre', 'Autre')], default='autre', max_length=40, verbose_name="Type d'action")),
                ('description', models.TextField(verbose_name='Description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='User-Agent')),
                ('objet_type', models.CharField(blank=True, help_text='Ex: Produit, Entreprise, Utilisateur', max_length=100, verbose_name="Type d'objet concerné")),
                ('objet_id', models.CharField(blank=True, max_length=100, verbose_name="ID de l'objet concerné")),
                ('donnees_avant', models.JSONField(blank=True, null=True, verbose_name='Données avant modification')),
                ('donnees_apres', models.JSONField(blank=True, null=True, verbose_name='Données après modification')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_audit', to='entreprises.entreprise', verbose_name='Entreprise')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_audit', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Log d'audit",
                'verbose_name_plural': "Logs d'audit",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entreprise', '-created_at'], name='core_auditl_entrepr_b12de5_idx'), models.Index(fields=['utilisateur', '-created_at'], name='core_auditl_utilisa_af8707_idx'), models.Index(fields=['type_action'], name='core_auditl_type_ac_672518_idx')],
            },
        ),
    ]
