# Generated by Django 6.0.4 on 2026-04-14 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('entreprises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_export', models.CharField(choices=[('bc_csv', 'Bons de commande CSV'), ('bc_pdf', 'Bons de commande PDF'), ('fournisseurs_csv', 'Fournisseurs CSV'), ('predictions_csv', 'Prédictions CSV'), ('suggestions_csv', 'Suggestions CSV'), ('valorisation_cump_csv', 'Valorisation CUMP CSV'), ('marges_csv', 'Marges CSV'), ('rapport_comptable_pdf', 'Rapport comptable PDF'), ('depreciation_csv', 'Dépréciation CSV'), ('rapport_categories_pdf', 'Rapport par catégories PDF')], max_length=50)),
                ('nom_fichier', models.CharField(max_length=255)),
                ('periode', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='entreprises.entreprise')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
