# Generated by Django 6.0.4 on 2026-04-08 13:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=200)),
                ('type_entreprise', models.CharField(choices=[('commerce_detail', 'Commerce de détail'), ('gros_distribution', 'Gros / Distribution'), ('ecommerce', 'E-commerce / Logistique'), ('industrie', 'Industrie / Atelier'), ('sante', 'Santé / Pharmacie'), ('restauration', 'Hôtellerie / Restauration')], max_length=50)),
                ('pays', models.CharField(default='Togo', max_length=100)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('taille', models.CharField(blank=True, max_length=50)),
                ('nb_entrepots', models.PositiveIntegerField(default=1)),
                ('est_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
