# Generated by Django 6.0.4 on 2026-04-21 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0002_produit_prix_vente'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_recommandee', models.PositiveIntegerField()),
                ('raison', models.TextField(blank=True)),
                ('date_suggestion', models.DateField(auto_now_add=True)),
                ('priorite', models.CharField(choices=[('haute', 'Haute'), ('normale', 'Normale'), ('basse', 'Basse')], default='normale', max_length=20)),
                ('validee', models.BooleanField(default=False)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions_achat', to='stock.produit')),
            ],
        ),
    ]
